const albumAltTexts=[
    // Album1
        [
            "Blue-tone seaside port with many boats",
            "Blue-tone seaside port with many boats,slightly zoomed in",
            "Blue-tone seaside port with many boats,a closer view",
            "White church in front of blue sky background",
            "Old car hidden behind trees, covered with many stamps",
            "White building with the name of Whistle Bar, decorated with brown window frames",
            "Little Havana street scene with Cuba style buildings",
            "Building corner with pink gradient paints",
            "Store sign with pink heart-shaped neon light",
            "Building corner with a flag painting designed with beach scenes",
            "Street scenes with a mist produced by sprays",
            "pink building corner on blue sky background",
        ],
    // Album2
        [
            "Blue-tone seaside port with may boats",
            "Blue-tone seaside port with may boats",
            "Blue-tone seaside port with may boats",
            "White church in front of blue sky background",
            "Old car hidden behind trees, covered with many stamps",
            "White building with the name of Whistle Bar, decorated with brown window frames",
            "Little Havana street scene with Cuba style buildings",
            "Building corner with pink gradient paints",
            "Store sign with pink heart-shaped neon light",
            "Building corner with a flag painting designed with beach scenes",
            "Street scenes with a mist produced by sprays",
            "pink building corner on blue sky background",
        ],
    // Album3
        
        [
            "Blue-tone seaside port with may boats",
            "Blue-tone seaside port with may boats",
            "Blue-tone seaside port with may boats",
            "White church in front of blue sky background",
            "Old car hidden behind trees, covered with many stamps",
            "White building with the name of Whistle Bar, decorated with brown window frames",
            "Little Havana street scene with Cuba style buildings",
            "Building corner with pink gradient paints",
            "Store sign with pink heart-shaped neon light",
            "Building corner with a flag painting designed with beach scenes",
            "Street scenes with a mist produced by sprays",
            "pink building corner on blue sky background",
        ],
        // Album4
        [
            "Blue-tone seaside port with may boats",
            "Blue-tone seaside port with may boats",
            "Blue-tone seaside port with may boats",
            "White church in front of blue sky background",
            "Old car hidden behind trees, covered with many stamps",
            "White building with the name of Whistle Bar, decorated with brown window frames",
            "Little Havana street scene with Cuba style buildings",
            "Building corner with pink gradient paints",
            "Store sign with pink heart-shaped neon light",
            "Building corner with a flag painting designed with beach scenes",
            "Street scenes with a mist produced by sprays",
            "pink building corner on blue sky background",
        ],
        // Album5
        [
            "Blue-tone seaside port with may boats",
            "Blue-tone seaside port with may boats",
            "Blue-tone seaside port with may boats",
            "White church in front of blue sky background",
            "Old car hidden behind trees, covered with many stamps",
            "White building with the name of Whistle Bar, decorated with brown window frames",
            "Little Havana street scene with Cuba style buildings",
            "Building corner with pink gradient paints",
            "Store sign with pink heart-shaped neon light",
            "Building corner with a flag painting designed with beach scenes",
            "Street scenes with a mist produced by sprays",
            "pink building corner on blue sky background",
        ],
        // Album6
        [
            "Blue-tone seaside port with may boats",
            "Blue-tone seaside port with may boats",
            "Blue-tone seaside port with may boats",
            "White church in front of blue sky background",
            "Old car hidden behind trees, covered with many stamps",
            "White building with the name of Whistle Bar, decorated with brown window frames",
            "Little Havana street scene with Cuba style buildings",
            "Building corner with pink gradient paints",
            "Store sign with pink heart-shaped neon light",
            "Building corner with a flag painting designed with beach scenes",
            "Street scenes with a mist produced by sprays",
            "pink building corner on blue sky background",
        ],
        // Album7
        [
            "Blue-tone seaside port with may boats",
            "Blue-tone seaside port with may boats",
            "Blue-tone seaside port with may boats",
            "White church in front of blue sky background",
            "Old car hidden behind trees, covered with many stamps",
            "White building with the name of Whistle Bar, decorated with brown window frames",
            "Little Havana street scene with Cuba style buildings",
            "Building corner with pink gradient paints",
            "Store sign with pink heart-shaped neon light",
            "Building corner with a flag painting designed with beach scenes",
            "Street scenes with a mist produced by sprays",
            "pink building corner on blue sky background",
        ],
        
]