const albumAltTexts=[
    // Album1
        [
            "Blue-tone seaside port with many boats",
            "Blue-tone seaside port with many boats,slightly zoomed in",
            "Blue-tone seaside port with many boats,a closer view",
            "White church in front of blue sky background",
            "Old car hidden behind trees, covered with many stamps",
            "White building with the name of Whistle Bar, decorated with brown window frames",
            "Little Havana street scene with Cuba style buildings",
            "Building corner with pink gradient paints",
            "Store sign with pink heart-shaped neon light",
            "Building corner with a flag painting designed with beach scenes",
            "Street scenes with a mist produced by sprays",
            "pink building corner on blue sky background",
        ],
    // Album2
        [
            "Vast farm with water ponds, houses and a tower on blue sky background",
            "three trees inside a water pond, one full of green leaves and the other two are empty",
            "expanded view of three trees in a pond, a warehouse is beside the pond",
            "a warehouse with trees and ponds in the front",
            "a farm view with houses in the back and water pond in the front",
            "a red warehouse beside the road, with a forest behind it with no leaf",
            "Two ducks in the blue wavy water",
            "one view of the port, a house is behind the platforms",
            "A port with no boats, only wooden platforms and white poles",
            "a port with fairywheels and buildings behind the wooden platforms",
            "a tree with no leaf standing besides the road",
            "trees with no leaf standing in the yard covered by snow" 
        ],
    // Album3
        [
            "Detail view of a tree branch full of green leaves",
            "another view of the tree branch in front of blue sky background",
            "pink flowers in front of a house",
            "detail house window view in front of blue sky",
            "a house in the corner of the road, covered by shadows shed by a tree",
            "old pink car in front of a garage",
            "old pink car facing the camra",
            "close up view of the old pink car with polished details",
            "a green garden scene looking through a narrow corridoe",
            "Pittsburgh street views in a fall afternoon",
            "Andy Warhol Bridge in the golden hour near sunset",
            "close up view of a grass field with dandelions",
        ],
    // Album4
        [
            "pink and purple Sunset view near the golden gate bridge, birds flying across the screen",
            "close up view of golden gate bridge with see and mountains in the back",
            "close up view of golden gate bridge structure facing the sunset",
            "horizontal close up view of golden gate bridge structure",
            "vertical perspective of Golden gate bridge in front of purple and pink sky",
            "sea view in front of pink and purple sunset, a line of bird flying by",
            "a building in front of purple and pink sky",
            "seashore sunset view looking from mountain top",
            "horizontal perspective of golden gate bridge in purple and pink sky",
            "sunset view of mountains near the sea",
            "half-panorama view of the bay area with golden gate bridge",
            "a person sitting on top of the building in red and pink sunset sky",
        ],
    // Album5
        [
            "townhouses on the slope of San Francisco street",
            "view of california street down the slop with skyscrapers on sides and golden gate bridge in the back",
            "Blue-tone seaside port",
            "seaside port with many boats",
            "a different angle of port with boats",
            "Italy style restaurant with red umbrellas and yellow walls",
            "San Francisco Street with interesting cars on the road",
            "Walkway in a shopping district",
            "overview of San Francisco looking from a hilltop",
            "an old building with red roof in a port with boats",
            "far view of golden gate bridge from a mountain top",
            "a luxurious house with red roofs in front of a huge grass land",
        ],
    // Album6
        [
            "Buddhism white tower with buddhist banners in front of it",
            "close view of many colorful buddhist banners",
            "buddhist banners tied to a tree",
            "far view of a religous platform with white tower and a circle of colorful buddhist banners",
            "vertical view of white tower with buddhist banners in the front",
            "Shambhala mountain in Shangri-La, covered by snow, a wooden house in the front scene",
            "Songtsamling monastery, Lhasa, Tibet, in morning sunlight",
            "close up window frame of Tibet style vernacular buildings",
            "door frame detail of Tibet style vernacular buildings",
            "Corner view of Songtsamling monastery with golden religous towers on top",
            "building corner looking from below, yellow curtain and very detailed wood paintings",
            "buddhist monks in red clothes practicing for religous events",
        ],
    // Album7
        [
            "a bouquet in a shrubbery under golden sunset light",
            "Small white flowers detail view",
            "pink flowers detail view",
            "pink flowers in a building corner",
            "green leaves under blue sky",
            "view of grassland under sunset light, tips of grass become golden",
            "Pittsburgh cherry blossoms in front of Andy Warhol Bridge",
            "Pittsburgh street view besides the river under sunset light",
            "tiny pink flowers in a shrub of green leaves",
            "view of tree braches with green leaves under sunlight",
            "close up view of one dandelion under sunset light",
            "red trillium in a very sunny day",
        ],
        
]